### ISSUE TITLE
Can't use .list to get any object type from Blender 2.8 file

### ISSUE THREAD

**Issue by golyalpha** [gabdube/tinyblend#4]
When trying to load (for example) scenes from a Blender 2.8 file, this is what happens:
```py
>>> BlenderFile.list(blend, 'Scene')
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tinyblend.py", line 774, in list
    fact = BlenderObjectFactory(self, self.index.type_names.index(factory_name))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tinyblend.py", line 387, in __init__         self.object, _ = BlenderObjectFactory._build_objects(file, self.struct_dna)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tinyblend.py", line 349, in _build_objects
    dep = (BlenderObjectFactory._build_objects(file, tmp_dna)[0], slice(offset, offset+f.size), f.name)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tinyblend.py", line 356, in _build_objects
    fmt_names = namedtuple(name, fmt_names)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\collections\__init__.py", line 370, in namedtuple          raise ValueError('Field names cannot start with an underscore: '
ValueError: Field names cannot start with an underscore: '_pad'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\tinyblend.py", line 778, in list
    raise BlenderFileReadException('Data type {} could not be found in the blend file'.format(factory_name))
tinyblend.BlenderFileReadException: Data type Scene could not be found in the blend file
```

**Comment by gabdube** [comment]
I'll look into it. Maybe renaming the fields name that starts with "_" will be enough.

**Comment by gabdube** [comment]
Fixing the underscore worked. I've updated the package to "1.0.2" so ` pip install --upgrade tinyblend` should do the trick.

**Comment by golyalpha** [comment]
thx, will check

**Comment by Mimickal** [comment]
This seems to still be having trouble on certain fields. I get the following error when trying to list "Link":
```
>>> from tinyblend import BlenderFile
>>> blend = BlenderFile('./plane.blend')
>>> blend.list('Link')
<BlenderObjectFactory for 'Link' objects>
>>> for i in blend.list('Link'): print (i)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mia/.local/lib/python3.5/site-packages/tinyblend.py", line 421, in __iter__
    yield self.object(self._file, data)
  File "/home/mia/.local/lib/python3.5/site-packages/tinyblend.py", line 212, in __new__
    BlenderObject._set_fields(cls.FMT.names._fields, cls.FMT.unpack(data), obj)
  File "/home/mia/.local/lib/python3.5/site-packages/tinyblend.py", line 114, in unpack
    values = self.format.unpack(data)
struct.error: unpack requires a bytes object of length 16
```
I've attached the file I'm using to test. This was created with Blender 2.80. I'm using tinyblend version 1.0.2.
[plane.zip](https://github.com/gabdube/tinyblend/files/4158562/plane.zip)

**Comment by gabdube** [comment]
I will look into this.

**Comment by gabdube** [comment]
This is weird. The field type is 16 bytes, but data section for the links is 72 bytes. This usually means that there is more than one object in the data section, but 72 bytes is not a multiple of 16. It would work if the pointer fields were 4 byte instead of 8, but the blender file is x64.

**Comment by Mimickal** [comment]
I changed this function to pad the data to 16 bytes and use `unpack_from` instead of `unpack`. I'm guessing this probably introduces garbage data in the last Link, but this change does allow tinyblend to read all the Links in that file. The rest of the test suite passes with this change.
```
109     def unpack(self, data):                                                                          
110         x, y = len(data), self.format.size                                                           
111         if (x > y) and (x % y == 0):                                                                 
112             return tuple(self.iter_unpack(data))                                                     
113                                                                                                      
114         if x < y:                                                                                    
115             data += b'\0' * (y - x)                                                                  
116                                                                                                      
117         values = self.format.unpack_from(data)                                                       
118         return self.names(*values)
```

**Comment by gabdube** [comment]
I don't think this will work. After looking at the data .

```
\x01\x00\x00\x00\xfa\x00\x00\x00Scene\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
```

```
Link (VersionInfo(major=2, minor=8, rev=0))
|-- Link *next
|-- Link *prev
```

This does not look like the data of a Link object. Ex: there shouldn't be a "Scene" string in a struct made of two pointers. Looks like the library is trying to read from the wrong memory block.

Edit: also I forgot some base types, but that's not linked to the issue,

**Comment by gabdube** [comment]
Because this is not related to this particular issue, I created another one https://github.com/gabdube/tinyblend/issues/5
